name: Call refresh tokens

on:
  schedule:
    - cron: '25 7,15,23 * * *'

jobs:
  call-refresh-tokens:
    name: Call refresh tokens
    runs-on: ubuntu-latest

    steps:
      - name: Fetch cloud function to trigger tokens refresh
        env:
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          SERVER_OPERATOR_TOKEN: ${{ secrets.SERVER_OPERATOR_TOKEN }}
        run: |
          curl --silent --show-error --fail \
            -H "X-Operator-Token: $SERVER_OPERATOR_TOKEN" \
            -X POST https://us-central1-$FIREBASE_PROJECT_ID.cloudfunctions.net/app/ecom/refresh-tokens
